AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack for ECS Java ShutterBox App with S3, Auto Scaling, ALB, Code Deploy

Parameters:
  AppName:
    Type: String
    Default: shutter-box
  LabTag:
    Type: String
    Default: week_6_lab
  TemplateS3BaseURL:
    Description: 'S3 Base URL where nested templates are hosted'
    Type: String
    Default: 'https://shutterbox-cf-templates.s3.eu-west-1.amazonaws.com/v2-infra-templates'

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/s3-infra.yml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/vpc.yml"
      Parameters:
        AppName: !Ref AppName
        S3BucketName: !GetAtt S3Stack.Outputs.BucketName
        LabTag: !Ref LabTag

  ECSAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/ecs-cluster-alb-fargate.yml"
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        S3BucketName: !GetAtt S3Stack.Outputs.BucketName
        VPCEndpointSG: !GetAtt VPCStack.Outputs.VPCEndpointSecurityGroup
        AppName: !Ref AppName
        LabTag: !Ref LabTag

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECSAppStack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/ecs-codedeploy.yml"
      Parameters:
        ClusterName: !GetAtt ECSAppStack.Outputs.ClusterName
        ServiceName: !GetAtt ECSAppStack.Outputs.ServiceName
        TargetGroup1: !GetAtt ECSAppStack.Outputs.BlueTargetGroupName
        TargetGroup2: !GetAtt ECSAppStack.Outputs.GreenTargetGroupName
        ListenerArn: !GetAtt ECSAppStack.Outputs.ALBListenerArn
        AppName: !Ref AppName
        LabTag: !Ref LabTag

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CodeDeployStack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/code-pipeline.yml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        CodeDeployApplication: !GetAtt CodeDeployStack.Outputs.CodeDeployApplication
        CodeDeployDeploymentGroup: !GetAtt CodeDeployStack.Outputs.CodeDeployDeploymentGroup

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS to access app
    Value: !GetAtt ECSAppStack.Outputs.AppLoadBalancerDNS

  S3BucketName:
    Description: S3 bucket used by the app
    Value: !GetAtt S3Stack.Outputs.BucketName