AWSTemplateFormatVersion: "2010-09-09"
Description: Root Stack for ECS Java ShutterBox App with S3, Auto Scaling, ALB, Code Deploy

Parameters:
  AppName:
    Type: String
    Default: shutter-box
  LabTag:
    Type: String
    Default: week_6_lab
  TemplateS3BaseURL:
    Description: "S3 Base URL where templates are stored"
    Type: AWS::SSM::Parameter::Value<String>
    Default: /shutter-box/template-base-uri
  ECRImageUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /shutter-box/image-uri

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/s3-infra.yml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/vpc.yml"
      Parameters:
        AppName: !Ref AppName
        S3BucketName: !GetAtt S3Stack.Outputs.BucketName
        LabTag: !Ref LabTag

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/securitygroups.yml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        VPCEndpointSG: !GetAtt VPCStack.Outputs.VPCEndpointSG

  ECSAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RDSStack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/ecs-cluster-alb-fargate.yml"
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        S3BucketName: !GetAtt S3Stack.Outputs.BucketName
        VPCEndpointSG: !GetAtt VPCStack.Outputs.VPCEndpointSG
        ECSSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ECSSecurityGroup
        ALBSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroup
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        ECRImageUri: !Ref ECRImageUri

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECSAppStack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/ecs-codedeploy.yml"
      Parameters:
        ClusterName: !GetAtt ECSAppStack.Outputs.ClusterName
        ServiceName: !GetAtt ECSAppStack.Outputs.ServiceName
        TargetGroup1: !GetAtt ECSAppStack.Outputs.BlueTargetGroupName
        TargetGroup2: !GetAtt ECSAppStack.Outputs.GreenTargetGroupName
        ListenerArn: !GetAtt ECSAppStack.Outputs.ALBListenerArn
        AppName: !Ref AppName
        LabTag: !Ref LabTag

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CodeDeployStack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/code-pipeline.yml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        CodeDeployApplication: !GetAtt CodeDeployStack.Outputs.CodeDeployAppName
        CodeDeployDeploymentGroup: !GetAtt CodeDeployStack.Outputs.CodeDeployDeploymentGroupName

  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
    Properties:
      TemplateURL: !Sub "${TemplateS3BaseURL}/rds.yml"
      Parameters:
        AppName: !Ref AppName
        LabTag: !Ref LabTag
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        RdsSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.RdsSecurityGroup
        RdsVPCEndpointSG: !GetAtt SecurityGroupsStack.Outputs.RdsVPCEndpointSG
        VPCEndpointSG: !GetAtt VPCStack.Outputs.VPCEndpointSG

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS to access app
    Value: !GetAtt ECSAppStack.Outputs.AppLoadBalancerDNS

  S3BucketName:
    Description: S3 bucket used by the app
    Value: !GetAtt S3Stack.Outputs.BucketName
