AWSTemplateFormatVersion: '2010-09-09'
Description: Application S3 Bucket with policy

Parameters:
  AppName:
    Type: String

  LabTag:
    Type: String

Resources:
  ## S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}-v2-images
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins: ["*"]
            MaxAge: 3000
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-v2-images
        - Key: Lab
          Value: !Ref LabTag

Outputs:
  BucketName:
    Description: S3 bucket used by application
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AppName}-v2-images

  BucketArn:
    Description: ARN of the bucket
    Value: !GetAtt S3Bucket.Arn
