name: Upload and Deploy CloudFormation Templates

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload templates to S3
        run: |
          aws s3 cp infra-templates/ s3://${{ secrets.S3_BUCKET_NAME }}/v2-infra-templates/ --recursive --region ${{ secrets.AWS_REGION }}
      
      - name: Zip CodeDeploy files
        run: |
          cd pipeline-configs
          zip ../pipeline-configs.zip appspec.json taskdef.json
  
      - name: Upload pipeline-configs.zip to S3
        run: |
          aws s3 cp pipeline-configs.zip s3://${{ secrets.S3_BUCKET_NAME }}/v2-infra-templates/pipeline-configs.zip --region ${{ secrets.AWS_REGION }}